# Generated by Django 4.2.5 on 2024-06-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_remove_note_tags_note_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="blocks",
            field=models.JSONField(default=list),
        ),
    ]
