# Generated by Django 4.2.5 on 2024-06-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_remove_note_tags_note_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="local_avatar_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="remote_avatar_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="note",
            name="tags",
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="notes", to="notes.tag"
            ),
        ),
    ]
