# Generated by Django 4.2.5 on 2024-06-10 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0004_note_blocks"),
        ("notes", "0004_userprofile_local_avatar_url_and_more"),
    ]

    operations = []
