# Generated by Django 4.2.5 on 2024-06-11 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_merge_20240611_0025"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="blocks",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar",
        ),
    ]
